// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Onlyspans.Variables.Api.Data.Contexts;

#nullable disable

namespace Onlyspans.Variables.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Onlyspans.Variables.Api.Data.Entities.ProjectVariableSetLink", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VariableSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjectId", "VariableSetId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VariableSetId");

                    b.ToTable("ProjectVariableSetLinks");
                });

            modelBuilder.Entity("Onlyspans.Variables.Api.Data.Entities.Variable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VariableSetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VariableSetId");

                    b.HasIndex("ProjectId", "Key", "EnvironmentId");

                    b.HasIndex("VariableSetId", "Key", "EnvironmentId");

                    b.ToTable("Variables");
                });

            modelBuilder.Entity("Onlyspans.Variables.Api.Data.Entities.VariableSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("VariableSets");
                });

            modelBuilder.Entity("Onlyspans.Variables.Api.Data.Entities.ProjectVariableSetLink", b =>
                {
                    b.HasOne("Onlyspans.Variables.Api.Data.Entities.VariableSet", "VariableSet")
                        .WithMany()
                        .HasForeignKey("VariableSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VariableSet");
                });

            modelBuilder.Entity("Onlyspans.Variables.Api.Data.Entities.Variable", b =>
                {
                    b.HasOne("Onlyspans.Variables.Api.Data.Entities.VariableSet", "VariableSet")
                        .WithMany("Variables")
                        .HasForeignKey("VariableSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("VariableSet");
                });

            modelBuilder.Entity("Onlyspans.Variables.Api.Data.Entities.VariableSet", b =>
                {
                    b.Navigation("Variables");
                });
#pragma warning restore 612, 618
        }
    }
}
